INSERT INTO users (username, password, category, email, first_name, last_name, is_staff, is_active, is_superuser, last_login, date_joined) VALUES ('Machiavelli', 'nu45edi1', 'admin
', 'dmitryro@gmail.com', 'Nicollo', 'Machiavelli', TRUE, TRUE, TRUE, NOW(), NOW());
INSERT INTO users (username, password, category, email, first_name, last_name, is_staff, is_active, is_superuser, last_login, date_joined) VALUES ('Dmitryro', 'nu45edi1', 'admin
', 'dmitryro1@gmail.com', 'Dmitry', 'Roitman', TRUE, TRUE, TRUE, NOW(), NOW());

INSERT INTO sites(host, port, ip, ga, date_added, date_last_crawled) VALUES ('lovehate.io', '8080', '127.0.0.1', 'UI-201031', NOW(), NOW());
INSERT INTO sites(host, port, ip, ga, date_added, date_last_crawled) VALUES ('3dact.com', '8080', '127.0.0.1', 'UI-201032', NOW(), NOW());

INSERT INTO states (code, name) VALUES ('AL', 'Alabama');
INSERT INTO states (code, name) VALUES ('AK', 'Alaska');
INSERT INTO states (code, name) VALUES ('AZ', 'Arizona');
INSERT INTO states (code, name) VALUES ('AR', 'Arkansas');
INSERT INTO states (code, name) VALUES ('CA', 'California');
INSERT INTO states (code, name) VALUES ('CO', 'Colorado');
INSERT INTO states (code, name) VALUES ('CT', 'Connecticut');
INSERT INTO states (code, name) VALUES ('DE', 'Delaware');
INSERT INTO states (code, name) VALUES ('DC', 'District of Columbia');
INSERT INTO states (code, name) VALUES ('FL', 'Florida');
INSERT INTO states (code, name) VALUES ('GA', 'Georgia');
INSERT INTO states (code, name) VALUES ('HI', 'Hawaii');
INSERT INTO states (code, name) VALUES ('ID', 'Idaho');
INSERT INTO states (code, name) VALUES ('IL', 'Illinois');
INSERT INTO states (code, name) VALUES ('IN', 'Indiana');
INSERT INTO states (code, name) VALUES ('IA', 'Iowa');
INSERT INTO states (code, name) VALUES ('KS', 'Kansas');
INSERT INTO states (code, name) VALUES ('KY', 'Kentucky');
INSERT INTO states (code, name) VALUES ('LA', 'Louisiana');
INSERT INTO states (code, name) VALUES ('ME', 'Maine');
INSERT INTO states (code, name) VALUES ('MD', 'Maryland');
INSERT INTO states (code, name) VALUES ('MA', 'Massachusetts');
INSERT INTO states (code, name) VALUES ('MI', 'Michigan');
INSERT INTO states (code, name) VALUES ('MN', 'Minnesota');
INSERT INTO states (code, name) VALUES ('MS', 'Mississippi');
INSERT INTO states (code, name) VALUES ('MO', 'Missouri');
INSERT INTO states (code, name) VALUES ('MT', 'Montana');
INSERT INTO states (code, name) VALUES ('NE', 'Nebraska');
INSERT INTO states (code, name) VALUES ('NV', 'Nevada');
INSERT INTO states (code, name) VALUES ('NH', 'New Hampshire');
INSERT INTO states (code, name) VALUES ('NJ', 'New Jersey');
INSERT INTO states (code, name) VALUES ('NM', 'New Mexico');
INSERT INTO states (code, name) VALUES ('NY', 'New York');
INSERT INTO states (code, name) VALUES ('NC', 'North Carolina');
INSERT INTO states (code, name) VALUES ('ND', 'North Dakota');
INSERT INTO states (code, name) VALUES ('OH', 'Ohio');
INSERT INTO states (code, name) VALUES ('OK', 'Oklahoma');
INSERT INTO states (code, name) VALUES ('OR', 'Oregon');
INSERT INTO states (code, name) VALUES ('PA', 'Pennsylvania');
INSERT INTO states (code, name) VALUES ('PR', 'Puerto Rico');
INSERT INTO states (code, name) VALUES ('RI', 'Rhode Island');
INSERT INTO states (code, name) VALUES ('SC', 'South Carolina');
INSERT INTO states (code, name) VALUES ('SD', 'South Dakota');
INSERT INTO states (code, name) VALUES ('TN', 'Tennessee');
INSERT INTO states (code, name) VALUES ('TX', 'Texas');
INSERT INTO states (code, name) VALUES ('UT', 'Utah');
INSERT INTO states (code, name) VALUES ('VT', 'Vermont');
INSERT INTO states (code, name) VALUES ('VA', 'Virginia');
INSERT INTO states (code, name) VALUES ('WA', 'Washington');
INSERT INTO states (code, name) VALUES ('WV', 'West Virginia');
INSERT INTO states (code, name) VALUES ('WI', 'Wisconsin');
INSERT INTO states (code, name) VALUES ('WY', 'Wyoming');
INSERT INTO states (code, name) VALUES ('GU', 'Guam');
INSERT INTO states (code, name) VALUES ('AB', 'Alberta');
INSERT INTO states (code, name) VALUES ('BC', 'British Columbia');
INSERT INTO states (code, name) VALUES ('MB', 'Manitoba');
INSERT INTO states (code, name) VALUES ('NB', 'New Brunswick');
INSERT INTO states (code, name) VALUES ('NL', 'Newfoundland and Labrador');
INSERT INTO states (code, name) VALUES ('NT', 'Northwest Territories');
INSERT INTO states (code, name) VALUES ('NS', 'Nova Scotia');
INSERT INTO states (code, name) VALUES ('NU', 'Nunavut');
INSERT INTO states (code, name) VALUES ('ON', 'Ontario');
INSERT INTO states (code, name) VALUES ('PE', 'Prince Edward Island');
INSERT INTO states (code, name) VALUES ('QC', 'Québec');
INSERT INTO states (code, name) VALUES ('SK', 'Saskatchewan');
INSERT INTO states (code, name) VALUES ('YT', 'Yukon Territory');
